version: "3.7"
services:
  node:
    build: .
    env_file:
      - .env
    volumes:
      - react-volume:/app/packages/client/dist
  nginx:
    image: nginx:1.17-alpine
    env_file:
      - .env
    volumes:
      - react-volume:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - node

volumes:
  react-volume:
