version: "3.7"
services:
  node:
    build:
      context: .
      dockerfile: node.Dockerfile
    env_file:
      - .env
    volumes:
      - react-volume:/app/packages/client/dist
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    env_file:
      - .env
    volumes:
      - react-volume:/usr/share/nginx/html:ro
    ports:
      - 80:80
    depends_on:
      - node

volumes:
  react-volume:
