version: "3.7"
services:
  node:
    build:
      context: ..
      dockerfile: lcldev/Dockerfile
    env_file:
      - .env
    ports:
    - 443:3001
    - 3001:3001
    volumes:
      - ..:/app
      - /app/node_modules
